# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1makzoQdpOXViA9rTcdvZHn58EOXVV_cM
"""

!pip install ultralytics streamlit pillow
from google.colab import drive
drive.mount('/content/drive')

streamlit_code = """
import streamlit as st
from ultralytics import YOLO
from PIL import Image

class_to_disease = {
    0: 'Bacterial Dermatosis',
    1: 'Flea Allergy',
    2: 'Fungal Infections',
    3: 'Healthy Cat Skin',
    4: 'Healthy Dog Skin',
    5: 'Hypersensitivity Allergic Dermatosis',
    6: 'Ringworm',
    7: 'Scabies'
}

# buat page title
st.set_page_config(page_title="AnabulCare", layout="wide")

# bagian atas
st.markdown(
    '''
    <div style="text-align: left; padding-top: 10px;">
        <h1>AnabulCare</h1>
    </div>
    ''', unsafe_allow_html=True)

# tulisan buat upload image
st.markdown(
    '''
    <div style="text-align: center; margin-top: 20px;">
        <h3>Upload Foto Kulit Anabul Kamu</h3>
        <p>Unggah gambar untuk mendeteksi penyakit kulit pada anabulmu menggunakan AI.</p>
    </div>
    ''', unsafe_allow_html=True)

# upload image
uploaded_file = st.file_uploader("Pilih file gambar (format .jpg, .jpeg, .png)", type=["jpg", "jpeg", "png"])

# cek udah upload
if uploaded_file is not None:
    # load image
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar yang diunggah", use_container_width=True)

    # load yolo
    st.markdown("<h4 style='text-align: center;'>Memproses gambar...</h4>", unsafe_allow_html=True)
    model = YOLO("best.pt")

    # predict
    results = model(image, imgsz=640)

    # buat display prediction
    st.markdown("<h4 style='text-align: center;'>Hasil Deteksi</h4>", unsafe_allow_html=True)
    detected_diseases = []
    for result in results:
      for box in result.boxes:
        disease_label = box.cls
        confidence = float(box.conf)

        # kasih nama berdasarkan label
        disease_name = class_to_disease.get(int(disease_label), "Unknown")
        detected_diseases.append(f"**Penyakit:** {disease_name} - **Kepercayaan:** {confidence:.2f}")

    # display penyakit
    if detected_diseases:
        for disease in detected_diseases:
            st.markdown(disease)
    else:
        st.markdown("<h4 style='text-align: center;'>Tidak ada penyakit yang terdeteksi.</h4>", unsafe_allow_html=True)

    # display image hasil
    st.image(results[0].plot(), caption="Hasil Deteksi", use_container_width=True)
else:
    st.markdown("<h4 style='text-align: center;'>Unggah gambar untuk mulai deteksi.</h4>", unsafe_allow_html=True)
"""

with open("app.py", "w") as f:
    f.write(streamlit_code)

!streamlit run app.py & npx localtunnel@2.0.2 --port 8501 --yes